//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupLevel
    {
        public GroupLevel()
        {
            this.GroupLevel1 = new HashSet<GroupLevel>();
            this.RoleGroupLevels = new HashSet<RoleGroupLevel>();
            this.UserGroupLevels = new HashSet<UserGroupLevel>();
        }
    
        public long id { get; set; }
        public Nullable<long> id_group { get; set; }
        public Nullable<long> id_parent { get; set; }
        public string remark { get; set; }
    
        public virtual ICollection<GroupLevel> GroupLevel1 { get; set; }
        public virtual GroupLevel GroupLevel2 { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<RoleGroupLevel> RoleGroupLevels { get; set; }
        public virtual ICollection<UserGroupLevel> UserGroupLevels { get; set; }
    }
}
