//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuApp
    {
        public MenuApp()
        {
            this.MenuApp1 = new HashSet<MenuApp>();
        }
    
        public int ID { get; set; }
        public string MenuTag { get; set; }
        public string MenuText { get; set; }
        public string FormName { get; set; }
        public Nullable<int> IDParentMenu { get; set; }
        public byte[] IconMenu { get; set; }
        public Nullable<int> OrderSort { get; set; }
    
        public virtual ICollection<MenuApp> MenuApp1 { get; set; }
        public virtual MenuApp MenuApp2 { get; set; }
    }
}
