//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppAspNet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAppEntities : DbContext
    {
        public MyAppEntities()
            : base("name=MyAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChatMessage> ChatMessages { get; set; }
        public DbSet<ErrorReport> ErrorReports { get; set; }
        public DbSet<GroupLevel> GroupLevels { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<kategori> kategoris { get; set; }
        public DbSet<LogApp> LogApps { get; set; }
        public DbSet<MenuApp> MenuApps { get; set; }
        public DbSet<RoleGroupLevel> RoleGroupLevels { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<SettingApp> SettingApps { get; set; }
        public DbSet<UserGroupLevel> UserGroupLevels { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
