//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppAspNet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAppEntities : DbContext
    {
        public MyAppEntities()
            : base("name=MyAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessage> ChatMessage { get; set; }
        public virtual DbSet<ErrorReport> ErrorReport { get; set; }
        public virtual DbSet<GroupLevel> GroupLevel { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<LogApp> LogApp { get; set; }
        public virtual DbSet<MenuApp> MenuApp { get; set; }
        public virtual DbSet<RoleGroupLevel> RoleGroupLevel { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SettingApp> SettingApp { get; set; }
        public virtual DbSet<UserGroupLevel> UserGroupLevel { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
