//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.RoleGroupLevels = new HashSet<RoleGroupLevel>();
            this.UserRoles = new HashSet<UserRole>();
            this.MenuApps = new HashSet<MenuApp>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string note { get; set; }
        public string url { get; set; }
        public string controller { get; set; }
        public bool AccessView { get; set; }
        public bool AccessAdd { get; set; }
        public bool AccessEdit { get; set; }
        public bool AccessDelete { get; set; }
        public bool AccessPrint { get; set; }
        public bool AccessCustom { get; set; }
    
        public virtual ICollection<RoleGroupLevel> RoleGroupLevels { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<MenuApp> MenuApps { get; set; }
    }
}
