//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public long id { get; set; }
        public Nullable<long> id_user { get; set; }
        public Nullable<long> id_role { get; set; }
        public Nullable<bool> allow_view { get; set; }
        public Nullable<bool> allow_add { get; set; }
        public bool allow_update { get; set; }
        public Nullable<bool> allow_delete { get; set; }
        public Nullable<bool> allow_print { get; set; }
        public Nullable<int> allow_custom_access { get; set; }
    
        public virtual User User { get; set; }
        public virtual Role Role { get; set; }
    }
}
