//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppAspNet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroupLevel
    {
        public long id { get; set; }
        public Nullable<long> id_user { get; set; }
        public Nullable<long> id_group_level { get; set; }
    
        public virtual GroupLevel GroupLevel { get; set; }
        public virtual User User { get; set; }
    }
}
